### ISSUE TITLE
Team #145  the galbas

### ISSUE THREAD

**Issue by ahmetbozaci** [IjayAbby/Web-Scraper-Ruby-Capstone-Project#5]
- Your codebase looks good but I encountered an error while running `ruby bin/main.rb`: "/Users/apple/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:200:in `connect_until_stable': unable to connect to chromedriver 127.0.0.1:9515 (Selenium::WebDriver::Error::WebDriverError)" Is there a config I need to do on my system? I tried using the webdrivers gem and installing it again using `brew cask install chromedriver` which installed successfully but still not working. Kindly update your code to fix the chromedriver issue.

- It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history (screenshot from Pathwright) Check: lib/page_contents.rb line 3 and 33, also lib/scraper.rb:4 and bin/main.rb:53

**Comment by IjayAbby** [comment]
I have fixed the error and the project is complete and approved.
